# Generated by Django 3.2.8 on 2021-10-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('slug', models.SlugField(verbose_name='Atalho')),
                ('descripton', models.TextField(verbose_name='Descricao, blank=True')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='data de inicio')),
                ('image', models.ImageField(upload_to='couses/image', verbose_name='imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='atualizado em')),
            ],
        ),
    ]
